### ISSUE TITLE
Overhaul with new Samtools source code

### ISSUE THREAD

**Issue by kjohnsen** [Bioconductor/Rsamtools#2]
In my lab we are trying to replace what was once a Python script with an R package, and where we were using Samtools we are now using Rsamtools. We are realizing our analysis doesn't work well using Rsamtools because it's missing some of the relatively new functionality of Samtools, namely incorporating the BAQ computation in `mpileup`. This has been our experience, but I'm sure Rsamtools is missing features important to others as well which have been added to Samtools in recent years, and thus are not found in the old Samtools C code Rsamtools is built on.

**Comment by mtmorgan** [comment]
There are two components here. The first is updating current code to use newer htslib; this has started via [Rhtslib][1], but there is significant work to be done in Rsamtools. The second is to implement new(er) functionality sucha s BAQ computation. This will be a long process.

[1]: https://bioconductor.org/packages/devel/Rhtslib

**Comment by kjohnsen** [comment]
Okay, glad to hear it's being worked on. Thank you for the update!
