### ISSUE TITLE
ScanBamParams documentation

### ISSUE THREAD

**Issue by cmatKhan** [Bioconductor/Rsamtools#25]
I've found the documentation on the usage of ScanBamParams to be opaque. In particular, it wasn't immediately apparent to me that these arguments:

```

isPaired | A logical(1) indicating whether unpaired (FALSE), paired (TRUE), or any (NA) read should be returned.
-- | --
isProperPair | A logical(1) indicating whether improperly paired (FALSE), properly paired (TRUE), or any (NA) read should be returned. A properly paired read is defined by the alignment algorithm and might, e.g., represent reads aligning to identical reference sequences and with a specified distance.

isUnmappedQuery | A logical(1) indicating whether unmapped (TRUE), mapped (FALSE), or any (NA) read should be returned.

hasUnmappedMate | A logical(1) indicating whether reads with mapped (FALSE), unmapped (TRUE), or any (NA) mate should be returned.

...
```

In the docs needed to be wrapped in a flag argument like so:

```
p2 <- ScanBamParam(what=scanBamWhat(),
                   flag=scanBamFlag(isMinusStrand=FALSE))
```

Clearly, I figured it out, mostly thanks to the online documentation here: https://www.rdocumentation.org/packages/Rsamtools/versions/1.24.0/topics/ScanBamParam

So it wasn't too hard to find good examples. But, I think the documentation could be improved in this section.

**Comment by mtmorgan** [comment]
It can be very hard to know, from 'up close', when documentation is confusing versus clear. If you have specific suggestions, perhaps you could provide a 'pull request' on the relevant file, https://github.com/Bioconductor/Rsamtools/blob/master/man/ScanBamParam-class.Rd.
