### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by sunnyyakima** [Bioconductor/Rsamtools#29]
here is the error message:

installing to /home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-Rsamtools/00new/Rsamtools/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘Rsamtools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-Rsamtools/00new/Rsamtools/libs/Rsamtools.so':
  /home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-Rsamtools/00new/Rsamtools/libs/Rsamtools.so: undefined symbol: tbx_conf_gff
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/Rsamtools’
The downloaded source packages are in
	‘/scratch/tmp/RtmpJyaMTr/downloaded_packages’
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, lattice, MASS,
    Matrix, mgcv, nlme, nnet, spatial, survival
  path: /usr/lib/R/site-library

sessionInfo() 
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=C.UTF-8            LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rhtslib_1.22.0 devtools_2.3.1 usethis_1.6.1 

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1      zlibbioc_1.36.0     pkgload_1.1.0      
 [4] R6_2.5.1            rlang_0.4.12        tools_4.0.2        
 [7] pkgbuild_1.0.8      sessioninfo_1.1.1   cli_3.1.0          
[10] withr_2.4.2         ellipsis_0.3.2      remotes_2.4.1      
[13] digest_0.6.28       assertthat_0.2.1    rprojroot_2.0.2    
[16] crayon_1.4.2        processx_3.4.3      BiocManager_1.30.16
[19] callr_3.4.3         fs_1.5.0            ps_1.3.3           
[22] testthat_2.3.2      curl_4.3.2          memoise_1.1.0      
[25] glue_1.4.2          compiler_4.0.2      desc_1.2.0         
[28] prettyunits_1.1.1  

Here is output from ldd:
ldd Rsamtools.so
	linux-vdso.so.1 (0x00007fffe8fc0000)
	libR.so => /usr/lib/libR.so (0x00007f162daba000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f162d8cc000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f162d8b1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f162d6c0000)
	libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f162d465000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f162d316000)
	libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8 (0x00007f162d2c4000)
	libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f162d23f000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f162d019000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f162ce09000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f162cbec000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f162cbe6000)
	libicuuc.so.67 => /usr/lib/x86_64-linux-gnu/libicuuc.so.67 (0x00007f162c9f8000)
	libicui18n.so.67 => /usr/lib/x86_64-linux-gnu/libicui18n.so.67 (0x00007f162c6e6000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f162c6ac000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f162c689000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f162dfcd000)
	libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f162a3e3000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f162a3b1000)
	libicudata.so.67 => /usr/lib/x86_64-linux-gnu/libicudata.so.67 (0x00007f1628898000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f16284b9000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f162846f000)

**Comment by sunnyyakima** [comment]
more info:

> so_file <- file.path(installed.packages()['Rhtslib','LibPath'], 
+                      'Rhtslib', 'usrlib', 'libhts.so.2')
> grep(pattern = "tbx_conf_gff", x = system2("nm", so_file, stdout = TRUE),  
+      value = TRUE )
[1] "0000000000097830 R tbx_conf_gff"


seems tbx_conf_gff is not missing.

**Comment by mtmorgan** [comment]
Is this because `BiocManager::valid()` reports problems, eg. with Rhtslib?

**Comment by sunnyyakima** [comment]
BiocManager::valid()
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org


* sessionInfo()

R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=C.UTF-8            LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rhtslib_1.22.0 devtools_2.3.1 usethis_1.6.1 

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1      zlibbioc_1.36.0     pkgload_1.1.0      
 [4] R6_2.5.1            rlang_0.4.12        tools_4.0.2        
 [7] pkgbuild_1.0.8      sessioninfo_1.1.1   cli_3.1.0          
[10] withr_2.4.2         ellipsis_0.3.2      remotes_2.4.1      
[13] digest_0.6.28       assertthat_0.2.1    rprojroot_2.0.2    
[16] crayon_1.4.2        processx_3.4.3      BiocManager_1.30.16
[19] callr_3.4.3         fs_1.5.0            ps_1.3.3           
[22] testthat_2.3.2      curl_4.3.2          memoise_1.1.0      
[25] glue_1.4.2          compiler_4.0.2      desc_1.2.0         
[28] prettyunits_1.1.1  

Bioconductor version '3.12'

  * 184 packages out-of-date
  * 0 packages too new

create a valid installation with

  BiocManager::install(c(
    "ape", "backports", "BH", "Biobase", "BiocGenerics", "bit", "bit64",
    "bitops", "blob", "broom", "callr", "car", "caTools", "cli", "clipr",
    "coda", "colorspace", "colourpicker", "conquer", "corrplot", "covr",
    "cowplot", "crayon", "crosstalk", "curl", "data.table", "DBI", "dbplyr",
    "deldir", "DEoptimR", "desc", "devtools", "diffobj", "digest", "diptest",
    "DNAcopy", "doParallel", "dplyr", "dqrng", "DT", "e1071", "ellipsis",
    "expm", "fansi", "farver", "fastICA", "fastmap", "fitdistrplus", "flexmix",
    "forcats", "foreach", "Formula", "fpc", "fs", "future", "future.apply",
    "gdtools", "generics", "ggplot2", "ggrepel", "ggridges", "ggsignif", "gh",
    "git2r", "globals", "glue", "gplots", "graph", "gtools", "haven", "hdf5r",
    "hexbin", "highr", "Hmisc", "hms", "htmlTable", "htmltools", "htmlwidgets",
    "httpuv", "httr", "igraph", "isoband", "iterators", "jpeg", "jsonlite",
    "knitr", "labeling", "later", "leiden", "lifecycle", "limma", "littler",
    "lme4", "lmtest", "lubridate", "magrittr", "maptools", "MatrixModels",
    "matrixStats", "mclust", "memoise", "mime", "mvtnorm", "openssl",
    "openxlsx", "patchwork", "pbapply", "pbkrtest", "pillar", "pkgbuild",
    "pkgKitten", "pkgload", "plotly", "processx", "promises", "proxy", "ps",
    "quantreg", "R.methodsS3", "R.oo", "R6", "rappdirs", "RBGL", "rcmdcheck",
    "Rcpp", "RcppAnnoy", "RcppArmadillo", "RcppEigen", "RcppParallel", "readr",
    "remotes", "reprex", "reticulate", "rio", "rjags", "rlang", "rmarkdown",
    "robustbase", "roxygen2", "rprojroot", "rstatix", "rstudioapi", "rsvd",
    "rversions", "rvest", "sandwich", "sctransform", "Seurat", "sf", "shiny",
    "shinyjs", "sitmo", "slam", "sodium", "sp", "SparseM", "statmod",
    "stringi", "svglite", "sys", "systemfonts", "testit", "testthat", "tibble",
    "tidyr", "tidyselect", "tidyverse", "tinytex", "units", "usethis", "utf8",
    "uwot", "vctrs", "vdiffr", "vegan", "VennDiagram", "VGAM", "viridis",
    "viridisLite", "withr", "xfun", "XML", "zip", "zoo"
  ), update = TRUE, ask = FALSE)

more details: BiocManager::valid()$too_new, BiocManager::valid()$out_of_date

Warning message:
184 packages out-of-date; 0 packages too new

**Comment by mtmorgan** [comment]
Yikes! If it were me and I did not have critical work pending, I would start by updating package `BiocManager::install(ask = FALSE)`. But actually when I look at the out-of-date packages I do not see the most likely culprit -- Rhtslib -- so I might first make sure that there was just a single installation of this package in `.libPaths()`.  And I might also want to know whether there were network file systems involved.

**Comment by sunnyyakima** [comment]
Rhtslib is only installed in my /home
it is a remote system in which I tried to install "Rsamtools", and I am a regular user, I guess there are network file systems

**Comment by sunnyyakima** [comment]
a little progress:

ls -lrth  /home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib/*/*.so 
-rwxr-xr-- 1 yu_liu yu_liu 3.7M Oct 30 10:47 /home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib/usrlib/libhts.so
-rwxr-xr-- 1 yu_liu yu_liu 2.7M Oct 30 10:47 /home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib/libs/Rhtslib.so

nm  /home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib/usrlib/libhts.so  | grep  tbx_conf_gff
0000000000097830 R tbx_conf_gff
nm  /home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib/libs/Rhtslib.so   | grep  tbx_conf_gff
# nothing from last command

so there are two Rhtslib.so in my /home, one of them has "tbx_conf_gff", but it is not reachable. 
Also, seems all other lib have similar path:
x86_64-pc-linux-gnu-library/4.0/XXXXlib/lib/XXXX.so
the Rhtslib with "tbx_conf_gff" has path with different pattern:
/home/yu_liu/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib/**usr**lib/libhts.so

**Comment by hpages** [comment]
Hi @sunnyyakima , were you able to solve this? Thanks
