### ISSUE TITLE
Support for delimited tags

### ISSUE THREAD

**Issue by joegeorgeson** [Bioconductor/Rsamtools#45]
Dear Rsamtools team,

I am trying to use the below to retrieve reads that are tagged as duplicates with picard, and distinguished by type with either 'DT:Z:SQ' or 'DT:Z:LB' (default of picard) as optional tags. If I am doing something wrong, can you please advise? If this is not currently supported, can you add a feature for this? If I enter the full tag, I get an error`Error in validObject(.Object) : invalid class “ScanBamParam” object: 'tag' must be two letters, e.g,, 'MD'` 

```
> DT <- ScanBamParam(tag=c("DT"), what="flag")
> bam.DT <- scanBam(bamFile, param=DT)
> str(bam.DT[[1]][["tag"]])
List of 1
 $ DT: NULL
```

**Comment by mtmorgan** [comment]
`ScanBamParam(tag="DT", what="flag")` is correct, as illustrated in this snippet from `example(ScanBamParam)`
```
ScnBmP> fl <- system.file("extdata", "ex1.bam", package="Rsamtools",
ScnBmP+                   mustWork=TRUE)
ScnBmP> p4 <- ScanBamParam(tag=c("NM", "H1"), what="flag")
ScnBmP> bam4 <- scanBam(fl, param=p4)
ScnBmP> str(bam4[[1]][["tag"]])
List of 2
 $ NM: int [1:3307] 0 0 0 5 0 1 0 1 0 1 ...
 $ H1: int [1:3307] 0 0 0 0 0 1 0 1 0 0 ...
```
An artificial example constructed with `DT:Z:foo` tags works for me.

Are there sequence names in the file (`seqnames(BamFile(bamFile))`)? Do other tags work?

**Comment by joegeorgeson** [comment]
Thanks for the quick reply!

> Are there sequence names in the file (`seqnames(BamFile(bamFile))`)?

No, this is what I see;
```
> bamFile
class: BamFile 
path: ~/Aligned.sortedByCoord.out.picard.bam
index: NA
isOpen: FALSE 
yieldSize: NA 
obeyQname: FALSE 
asMates: FALSE 
qnamePrefixEnd: NA 
qnameSuffixStart: NA 

> seqnames(bamFile)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"BamFile"’
```



> Do other tags work?

Yes, example below. Also, the 'DT' tags do exist in the file upon manual inspection...is there any chance a bitwise flag could impact this? I'm asking because I elsewhere (not in Rsamtools) encountered filtering based on duplicate bitwise flags.

```
> PG <- ScanBamParam(tag=c("PG"), what="flag")
> bam.PG <- scanBam(bamFile, param=PG)
> str(bam.PG[[1]][["tag"]])
List of 1
 $ PG: chr [1:119553466] "MarkDuplicates" "MarkDuplicates" "MarkDuplicates" "MarkDuplicates" ...
```

**Comment by mtmorgan** [comment]
Sorry that should have been `seqlevels(bamFile)` or `seqlevels(bamFile)` but probably they are there since the other tags work. 

Can you try reading only a portion of your bam file
```
bamFile <- BamFile(fl, yieldSize = 10000)
param <- ScanBamParam(tag=c("DT", "PG"))
str(scanBam(bamFile, param = param))
```

Or perhaps can you share some of your bam file with me?
