### ISSUE TITLE
using multiple threads for bam sorting, merging, and indexing

### ISSUE THREAD

**Issue by kriemo** [Bioconductor/Rsamtools#46]
**Is your feature request related to a problem? Please describe.**
No, not a problem. However, samtools supports using multiple threads for some operations and as far as i can tell Rsamtools doesn't provide this as an option. 

**Describe the solution you'd like**
Updating the bam sorting, indexing, and merging Rsamtools code to call newer samtools/htslib functions that provide a `nthreads` option. Exposing other new options available (such as sorting a BAM by tag value) could also be useful. 

e.g.
for sorting use [`bam_sort_core_ext`](https://github.com/Bioconductor/Rhtslib/blob/557aadb59f9fe048e6ebcbeb903a453d92a8a7f3/inst/include/bam_sort.c#L2414) rather than `bam_sort_core`
for merging use [`bam_merge_core2`](https://github.com/Bioconductor/Rhtslib/blob/557aadb59f9fe048e6ebcbeb903a453d92a8a7f3/inst/include/bam_sort.c#L999) rather than `bam_merge_core`
for indexing call [`sam_index_build3`](https://github.com/Bioconductor/Rhtslib/blob/557aadb59f9fe048e6ebcbeb903a453d92a8a7f3/src/htslib-1.15.1/htslib/sam.h#L1247)  rather than `bam_index_build`

The sorting, merging, and indexing operations are mostly external calls to htslib/samtools code so they seem to be the most straightforward places to start adding updated options.  

**Describe alternatives you've considered** 
Using samtools at the command-line instead works fine if these options are needed. 

**Additional context**
I could work on this and submit a PR if there is interest in these features.

**Comment by mtmorgan** [comment]
closed with https://github.com/Bioconductor/Rsamtools/pull/49
