### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by cmfield** [Bioconductor/Rsamtools#47]
**Describe the bug**
When the lazy loading stage is reached it crashes:

```** byte-compile and prepare package for lazy loading
sh: line 1: 76963 Illegal instruction     (core dumped) R_TESTS= '/nfs/nas22/fs2201/biol_micro_unix_modules/modules/software/R/4.2.0-foss-2020b/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmphinURs/file12a391a5471f1'

 *** caught illegal operation ***
address 0x7f4211cafcd0, cause 'illegal operand'
```

**To Reproduce**
BiocManager::install("Rsamtools")

**sessionInfo**
```R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /nfs/nas22/fs2201/biol_micro_unix_modules/modules/software/OpenBLAS/0.3.12-GCC-10.2.0/lib/libopenblas_haswellp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] BiocManager_1.30.19 compiler_4.2.0      tools_4.2.0
```

**Comment by mtmorgan** [comment]
You can 'see' that Rsamtools installs on the Bioconductor linux builder (under the current Bioc release using R-4.2 & [Bioc devel](http://bioconductor.org/checkResults/devel/bioc-LATEST/Rsamtools/) using R-devel, and that it installed under previous versions of Bioconductor including the versions that used R-4.2.0 ()

**Comment by cmfield** [comment]
Yes, and I actually managed to install it on another machine. Is it possible that an older chipset (~5yrs) could have a problem?

**Comment by mtmorgan** [comment]
My guess would be the /nfs mount

**Comment by cmfield** [comment]
> My guess would be the /nfs mount. You say 'lazy load'; can you elaborate? Is it at this stage here...
> 
> ```
> * installing *source* package ‘Rsamtools’ ...
> ** using staged installation
> ** libs
> ...
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> <illegal instruction here ???>
> ...
> ```

Yes, exactly at that point.

**Comment by cmfield** [comment]
Thanks, I'll give it a go.

**Comment by mtmorgan** [comment]
Is this issue still active?

**Comment by cmfield** [comment]
Well, I still could not get to install on the first machine and I suspect it's the chipset not supporting a recent core library because it's otherwise identical to the newer machine on which it did install - nothing I can put my finger on, but maybe a cautionary tale for others. Feel free to close the issue.
