### ISSUE TITLE
samtools markdup in Rsamtools

### ISSUE THREAD

**Issue by Adnanhashim** [Bioconductor/Rsamtools#51]
I'd like to use Rsamtools to remove duplicate reads from a bam file. I'm looking for a solution similar to samtools markdup -r -s in.bam out.bam. Can anyone tell me how to do this in R, preferably with Rsamtools.

thanks

**Comment by mtmorgan** [comment]
Better to ask on the support site https://support.bioconductor.org and tag with Rsamtools.

But in this case I don't think this is easily possible; one could create a filter in `filterBam()`, but that would likely be inconsistent in edge cases (what exactly is a 'duplicate' read?)
