### ISSUE TITLE
Help with pileup

### ISSUE THREAD

**Issue by joegeorgeson** [Bioconductor/Rsamtools#52]
Dear RSamtools,

I'm hoping to use the `pileup` function to output a table like the below. My goal is to be strand sensitive, distiguish +/- (for paired-end), include indels, as well count of 5'starts and 3'stops. I have so far been unsuccessful coming up with an implementation of `PileupParam` to retrieve this information. Are you able to help? Thanks!

```
chr loc ref strand  A   T   C   G   a   t   c   g   Insertion   Deletion    Stops   Starts
1   888659  T   +   0   9   0   2   0   0   0   0   2:AG|1:AGAG 1:ATT   3   2
```

**Comment by mtmorgan** [comment]
Hi @joegeorgeson please ask questions about software use on the Bioconductor [support site](https://support.bioconductor.org). Please remember to tag the question with the package you're asking about -- Rsamtools.
