### ISSUE TITLE
Compilation problem on macOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by mohammedemamkhattabunipd** [Bioconductor/Rsamtools#62]
**Describe the bug**
Trying to install Rsamtools through BiocManager, but im getting the following compilation error:

```
In file included from bam_mate_iter.cpp:2:
In file included from ./BamRangeIterator.h:7:
In file included from ./BamIterator.h:8:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/set:1761:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:526:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/boyer_moore_searcher.h:27:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:321:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__format/formatter_bool.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__format/formatter_integral.h:32:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/locale:202:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:1313:15: error:
   expected ';' at end of declaration list
  int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
```

**To Reproduce**
Run `BiocManager::install("Rsamtools")`.

**Expected behavior**
The package should be compiled correctly.

**sessionInfo**
Please report the output of `sessionInfo()` here.

```{r}
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin23.2.0 (64-bit)
Running under: macOS Sonoma 14.2.1

Matrix products: default
BLAS:   /opt/homebrew/Cellar/openblas/0.3.26/lib/libopenblasp-r0.3.26.dylib 
LAPACK: /opt/homebrew/Cellar/r/4.3.3/lib/R/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] C/UTF-8/C/C/C/C

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.22 compiler_4.3.3      tools_4.3.3  
```

**Comment by vjcitn** [comment]
Hi, sorry to hear about this; does your R configuration give answers consistent with those at https://bioconductor.org/checkResults/3.18/bioc-mac-arm64-LATEST/kjohnson1-NodeInfo.html ?

**Comment by hpages** [comment]
Any reason you need to compile **Rsamtools** yourself?

Compilation problems on Mac can be easily avoided by installing the package binaries that we provide. Note that installing package binaries is actually the default if you use the R binary for Mac arm64 available at https://cran.r-project.org/bin/macosx/ (pick up `R-4.3.3-arm64.pkg`). In addition to solving compilation issues, this makes package installations _much_ faster.

If for some reason using `R-4.3.3-arm64.pkg` is not an option for you, try `BiocManager::install("Rsamtools", type="mac.binary.big-sur-arm64")`.

**Comment by mohammedemamkhattabunipd** [comment]
It worked with `BiocManager::install("Rsamtools", type="mac.binary.big-sur-arm64")` thanks a lot.
